### ISSUE TITLE
Tarea MakeCode Arcade - Profesora Paula

### ISSUE THREAD

**Issue by Paula150395** [ULL-MFP-AET-2324/equipos-eq-paula-cristian#6]
Hola @CristianRA-1989 @OscarGarciaArteaga @crguezl,

Este es el enlace para acceder a la nueva tarea de MakeCode Arcade: https://classroom.github.com/a/7rxgjWNJ

Saludos!

**Comment by crguezl** [comment]
Buen trabajo 💯
